on:
  push:
    branches: [main]

name: macOS Build
jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/Library/Caches/Homebrew/*
            /tmp/package-*
            /usr/local/Cellar/*
            /usr/local/*
          key: brew-${{ runner.os }}-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-

      - name: Fetch dependencies
        run: |
          brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
          "$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
          brew install protobuf qbs qt5 kf5-kirigami2 kf5-kitemmodels || true
          brew link --force qt5

      - name: Build app
        run: |
          export QML2_IMPORT_PATH=/usr/local/lib/qt5/qml
          qbs project.vendoredKirigami:true
          mkdir -p ./default/Challah.81be376b/Challah.app/PlugIns/
          cp -r /usr/local/Cellar/qt/5.15.2/plugins/platforms ./default/Challah.81be376b/Challah.app/PlugIns/
          macdeployqt default/Challah.81be376b/Challah.app -qmldir=app/resources -dmg -verbose=3 $(find default/Challah.81be376b/Challah.app -name '*.dylib' -exec echo -n "-executable={} " \;)

      - name: DMG File
        uses: actions/upload-artifact@v2
        with:
          name: DMG File
          path: |
            default/Challah.81be376b/Challah.dmg
